### ISSUE TITLE
Slowness from max saved list items

### ISSUE THREAD

**Issue by tlannigan** [Friiiis/saved-posts-organizer#10]
Extension becomes very slow and unresponsive from my account. I have my saved posts maxed out, around 1000 items, and they are all loaded everytime I open the extension **and** when I sort into categories. Some sort of pagination, lazy-loading, or settings for maximum posts to see at a time might fix this issue.

**Comment by Friiiis** [comment]
The extension is not supposed to reload when sorting into categories. It will just continue the current loading session. This means that you should be able to do organize posts while it is loading.

**Comment by tlannigan** [comment]
I've captured a gif of the extension in action for you, maybe it'll explain what I'm talking about a bit better.

https://imgur.com/Kzt8knU

**Comment by Friiiis** [comment]
Yea, thats pretty bad. 

This happens because the extension has to create every single post (icon + link) and add it to the interface everytime it is opened. As your video shows, it only happens when your on "All posts" and "Uncategorized", which is the only two categories with hundreds of posts.

I think that I probably need to implement some sort of pagination like you said. That should fix it.

**Comment by Friiiis** [comment]
Version 1.1.13 has been approved on the Chrome Webstore. It introduces pagination when there is more than 50 posts in a category. I hope it closes the issue. 

Would you mind testing for me? Also let me know if the UX makes sense to you.

**Comment by tlannigan** [comment]
It's performing a lot better! It is, however, still freezing and becoming unresponsive right before the end of a sync for about 5-10s, and it tries to sync everytime I open it.

**Comment by Friiiis** [comment]
Glad to hear it made it better!
I will remove the automatic sync in the next update as it sounds like its pretty annoying when you have as many posts as you. I'm not sure why the sync makes it freeze, but I will look into it in another issue.
Thanks for the help here.
